version: 0.2
env:
  variables:
    ENVIRONMENT: "dev"
    CLUSTER_NAME: "nirucare-dev"
    BRANCH: "feature-branch001"
    DOCKER_REG: "myregistry"
phases:
  install: 
    commands: 
      - ls
  pre_build:
    commands:
      #- pip install --upgrade awscli
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 12345678.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
	  - whoami
	  - free -m
      - echo "Checking out to Branach"
      - ls -ltr
      - git checkout feature-branch001
      - GIT_BRANCH=`echo ${BRANCH} | tr '[:upper:]' '[:lower:]'`
      - echo Executing Docker Build `date`
      - IMAGE_ID="${ENVIRONMENT}"-"${CODEBUILD_BUILD_NUMBER}"
      - echo ${IMAGE_ID}
      - docker build -t ${IMAGE_ID} .
      - myID=`aws sts get-caller-identity --query Account --output text`
      - docker tag ${IMAGE_ID}:latest ${myID}.dkr.ecr.us-west-2.amazonaws.com/${DOCKER_REG}:${IMAGE_ID}
      - docker push ${myID}.dkr.ecr.us-west-2.amazonaws.com/${DOCKER_REG}:${IMAGE_ID}
      - sed -i -e "s/IMAGEIDPLACEHOLDER/${IMAGE_ID}/g" Task-definition-dev.json
      - aws ecs register-task-definition --cli-input-json Task-definition-dev.json
      - aws ecs update-service --cluster ${CLUSTER_NAME} --service niru-dev-service --task-definition smartapp-dev
  post_build:
    commands:
      - echo Deployed to ECS
