version: 0.2
env:
  variables:
    APP_NAME: "react-cicd-pipeline"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
      - npm install
  build:
    commands:
      - echo build process started now
 #     - npm run build  
#artifacts:
  # include all files required to run application
  # we include only the static build files
  #files:
  #  - '**/*'
  #base-directory: 'build'
